version: "3.8"

services:
  api:
    build: ./api
    command: python3 development.py
    volumes:
      - ./api:/api
    environment:
      - DATABASE_URL=mysql+pymysql://patrickarruda:cGF0cmlja2Fy@jobs.visie.com.br:3306/patrickarruda
    ports:
      - "8000:8000"
    working_dir: /api

  frontend:
    build: ./frontend
    command: serve -s dist/
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - VITE_API_URL=http://api:8000
    ports:
      - "3000:3000"
    working_dir: /frontend
    stdin_open: true
    tty: true

networks:
  default:
    name: visie
